name: Get Change
on: workflow_dispatch
jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Get Change Custom Action
              uses: ServiceNow/servicenow-devops-get-change@scratch_STRY55387904
              with:
                devops-integration-user-name: ${{ secrets.SN_DEVOPS_USER }}
                devops-integration-user-password: ${{ secrets.SN_DEVOPS_PASSWORD }}
                devops-integration-token: ${{ secrets.SECRET_TOKENS }}
                instance-url: ${{ secrets.SN_INSTANCE_URL }}
                tool-id: ${{ secrets.SN_ORCHESTRATION_TOOL_ID }}
                context-github: ${{ toJSON(github) }}
                job-name: 'Get Change'
                change-details: '{"pipeline_name":"maheshganji/custom-action-get/CustomActionGetWorkflow","stage_name":"ServiceNow Change Approval","build_number":"3732116819/attempts/1"}'
            - name: Output of GetChangeDetails
              run: echo "The Status of Update Change Request Details => ${{ steps.get.outputs.change-request-number }}"
